#!/bin/bash
rc=0

diff lib/test/test_userscript.html lib/test/test_userscript_grant.html
rc=$((rc+$?))

mapfile -t changed_files < <( git diff-index --name-only --cached HEAD )
python caps.py check "${changed_files[@]}"
rc=$((rc+$?))

if git diff --cached --name-only | grep -q '^.rogue/'; then
if pushd .rogue >/dev/null; then
	unittest -q
	rc=$((rc+$?))
	popd >/dev/null
fi
fi

if git diff --cached --name-only | grep -q '^lib/'; then

if pushd lib >/dev/null; then
	python -m compileall -q .
	rc=$((rc+$?))

	unittest -q -p py3 -p bash -p html # TODO option to exclude --platform py2
	rc=$((rc+$?))
	python -c "import clckwrkbdgr.buildqueue; clckwrkbdgr.buildqueue.run_command(['unittest', '-q', '-p', 'py2'], start_dir='$(pwd)')"
	rc=$((rc+$?))

	popd >/dev/null
fi

fi

[ $rc -gt 0 ] && echo "[Pre-commit failed with RC=$rc]"
exit $rc
