#!/bin/bash
rc=0

mapfile -t changed_files < <( git diff-index --name-only --cached HEAD )
python caps.py check "${changed_files[@]}"
rc=$((rc+$?))

if pushd lib >/dev/null; then
	unittest -q
	rc=$((rc+$?))
	popd >/dev/null
fi

[ $rc -gt 0 ] && echo "[Pre-commit failed with RC=$rc]"
exit $rc
