#!/bin/bash

voice() {
	IFS='\n'
	(
		echo '(voice_us1_mbrola)'
		echo '(set! default_after_synth_hooks (list (lambda (utt) (utt.wave.rescale utt 1.3 t))))'
		while read line; do
			echo '(SayText "'"$line"'")'
		done
	) | festival --pipe
}

if [ -z "$1" ]; then
	echo 'Oh.'
elif [ "$1" == "-" ]; then
	cat
else
	echo "$@"
fi | voice
