#!/bin/bash

voice() {
	espeak -ven+f3 -k 20 -m -p 99 -s 180
}

random_pitch() {
	word="$1"
	pitch=$(((($RANDOM) % 100) + 100))
	echo -n "<prosody pitch=\"$pitch\">$word</prosody> "
	echo "$word" | grep -q '[.]$' && echo
}

if [ -z "$1" ]; then
	echo 'Ouh.'
elif [ "$1" == "-" ]; then
	cat
else
	echo "$@"
fi | for word in `cat`; do
	random_pitch "$word"
done | voice

