#!/bin/bash
[ -f ~/.local/profile ] && source ~/.local/profile

is_scroll_led_on() {
	xset q | sed -n 4,9p | grep -o '[0-9][0-9]: [A-Za-z 0-9]\+: \+o[fn][f ]' | grep 'on $' | sed 's/.*: \([^:]\+\):.*/\1/' | grep -q 'Group 2'
}

get_all_pidgin_unread() {
	pgrep -x pidgin | while read pid; do
		wmctrl -l -p | grep ${pid} | awk '{print $1}' | while read window; do
			xprop -id ${window} | grep _PIDGIN_UNSEEN_COUNT | awk '{print $NF}'
		done
	done | paste -sd+ | bc
}

mini_johnny() {
	[ "$(get_all_pidgin_unread)" -gt 0 ] && echo -n '#' || echo -n ' '
	is_scroll_led_on && echo -n 'C' || echo -n ' '
}

get_leds() {
	xset q | sed -n 4,9p | grep -o '[0-9][0-9]: [A-Za-z 0-9]\+: \+o[fn][f ]' | grep 'on $' | sed 's/.*: \([^:]\+\):.*/\1/' | while read LED; do
		case "$LED" in
			Caps*) echo -n 'C' ;;
			Num*) echo -n 'N' ;;
			"Group 2") echo -n 'S' ;;
		esac
	done
}

leds() {
	LEDS=$(get_leds)
	echo "$LEDS" | grep -q 'N' && echo -n 'N' || echo -n ' '
	echo "$LEDS" | grep -q 'C' && echo -n 'C' || echo -n ' '
	echo "$LEDS" | grep -q 'S' && echo -n 'S' || echo -n ' '
}

alert() {
	if [ "$1" == "start" ]; then
		notify-send Pomodoro '<b>Take a break!</b>' --icon=gdu-smart-failing &
		aplay -q "$SIGNAL_SOUND" &
		glados 'Take a break!'
	elif [ "$1" == "stop" ]; then
		notify-send Pomodoro '<i>Now you can work again.</i>' --icon=gdu-smart-healthy
		aplay -q "$SIGNAL_SOUND" &
		glados 'Now you can work again.'
	elif [ "$1" == "alarm" ]; then
		notify-send Pomodoro '<i>Your single shot is fired.</i>' --icon=gnome-panel-clock
		aplay -q "$SIGNAL_SOUND" &
		glados 'Your single shot is fired.'
	elif [ -n "$1" ]; then
		notify-send "$*" &
		aplay -q "$SIGNAL_SOUND" &
		glados "$@"
	else
		aplay -q "$SIGNAL_SOUND"
	fi
}

ARG="$1"
shift
case "$ARG" in
	"mini") mini_johnny ;;
	"alert") alert "$@" ;;
	"leds") leds ;;
	*) echo 'Wat?' ;;
esac
