#!/bin/bash
is_scroll_led_on() {
	xset q | sed -n 4,9p | grep -o '[0-9][0-9]: [A-Za-z 0-9]\+: \+o[fn][f ]' | grep 'on $' | sed 's/.*: \([^:]\+\):.*/\1/' | grep -q 'Group 2'
}
get_all_pidgin_unread() {
	pgrep -x pidgin | while read pid; do
		wmctrl -l -p | grep ${pid} | awk '{print $1}' | while read window; do
			xprop -id ${window} | grep _PIDGIN_UNSEEN_COUNT | awk '{print $NF}'
		done
	done | paste -sd+ | bc
}
[ "$(get_all_pidgin_unread)" -gt 0 ] && echo -n '#' || echo -n ' '
is_scroll_led_on && echo -n 'C' || echo -n ' '
