#!/bin/bash

source ~/.bash_vars
[ -n "$2" ] && INTERFACE="-I $2"
COUNT=0
while true; do
	if ping -c 1 -s 1 -W 2 "$HOST" $INTERFACE >/dev/null 2>&1; then
		echo -n +
		COUNT=$((COUNT+1))
	else
		echo -n -
		COUNT=0
	fi
	[ $COUNT -gt 10 ] && aplay -q ~/owlwood/sounds/signal.wav
	sleep 3
done
