#!/bin/bash
get_leds() {
xset q | sed -n 4,9p | grep -o '[0-9][0-9]: [A-Za-z 0-9]\+: \+o[fn][f ]' | grep 'on $' | sed 's/.*: \([^:]\+\):.*/\1/' | while read LED; do
	case "$LED" in
		Caps*) echo -n 'C' ;;
		Num*) echo -n 'N' ;;
		"Group 2") echo -n 'S' ;;
	esac
done
}

LEDS=$(get_leds)
echo "$LEDS" | grep -q 'N' && echo -n 'N' || echo -n ' '
echo "$LEDS" | grep -q 'C' && echo -n 'C' || echo -n ' '
echo "$LEDS" | grep -q 'S' && echo -n 'S' || echo -n ' '
