#!/bin/bash

function list_all_left() {
	find -L . \! -executable | sort -f | grep -v 'sample' | egrep --color=never '(ogm|avi|mkv|mp4|wmv|mpg|mov)$'
}

if [ "x$1" == "x-l" ]; then
	list_all_left
	echo -n 'Series left: '
	list_all_left | wc -l
	exit 0
fi

next=$(list_all_left | head -1)
if [ -z "$next" ]; then
	ls -vRL --color=auto
	echo 'All done.'
	exit 1
fi
yes=y
if [ "x$1" == "x-i" ]; then
	shift;
	list_all_left
	echo
	echo "${next}, continue?"
	read yes
fi
if [ "$yes" = "y" ]; then
	mplayer $@ "$next" && chmod a+x "$next"
fi
