#!/bin/bash
CHANNEL=Master
STEP=2500
SHOW_POPUP=False

if [ "$1" == "up" ]; then
	amixer set "$CHANNEL" $STEP+ >/dev/null
elif [ "$1" == "down" ]; then
	amixer set "$CHANNEL" $STEP- >/dev/null
elif [ "$1" == "reset" ]; then
	amixer set "$CHANNEL" 30% >/dev/null
fi


VOLUME=$(amixer get "$CHANNEL" | sed '/^ *Front\ Left: /{s/^.*\[\(.*\)%\].*/\1/;p;};d;')
STATUS=$(amixer get "$CHANNEL" | awk '$2 == "Left:" { print $NF; }')
if [ "$STATUS" = '[off]' ]; then
    ICON=notification-audio-volume-muted
else
    if [ "$VOLUME" -eq 0 ]; then
        ICON=notification-audio-volume-off
    elif [ "$VOLUME" -lt 33 ]; then
        ICON=notification-audio-volume-low
    elif [ "$VOLUME" -lt 66 ]; then
        ICON=notification-audio-volume-medium
    else
        ICON=notification-audio-volume-high
    fi
	VOLUME=${VOLUME}%
fi
echo $VOLUME

[ "$SHOW_POPUP" == False ] && exit 0
notify-send "Volume" -i "$ICON" -h int:value:$VOLUME -h string:synchronous:volume
