#!/bin/bash
if [ "$1" == "up" ]; then
	amixer set Front 1+ >/dev/null
elif [ "$1" == "down" ]; then
	amixer set Front 1- >/dev/null
fi

VOLUME=$(amixer get Front | sed '/^ *Front\ Left: /{s/^.*\[\(.*\)%\].*/\1/;p;};d;')
STATUS=$(amixer get Front | awk '$2 == "Left:" { print $NF; }')
if [ $STATUS = '[off]' ]; then
    ICON=notification-audio-volume-muted
else
    if [ $VOLUME -eq 0 ]; then
        ICON=notification-audio-volume-off
    elif [ $VOLUME -lt 33 ]; then
        ICON=notification-audio-volume-low
    elif [ $VOLUME -lt 66 ]; then
        ICON=notification-audio-volume-medium
    else
        ICON=notification-audio-volume-high
    fi
	VOLUME=${VOLUME}%
fi
echo $VOLUME
notify-send "Volume" -i $ICON -h int:value:$VOLUME -h string:synchronous:volume
