export HISTCONTROL=ignoredups

. "$XDG_CONFIG_HOME/bash/aliases.inc.bash"

. "$XDG_CONFIG_HOME/bash/prompt.inc.bash"

# TODO temp measures until there is a way to update environment in running DE.
. ~/.config/lib/xdg.bash
for xdgsourcefile in ~/.config/xdg/*.sh; do
	grep -q '^deprecated' "$xdgsourcefile" && continue # TODO deprecated source files should be removed
	. "$xdgsourcefile"
done

# TODO have custom compat version of 'dircolors' to produce LS_COLORS in this case.
which dircolors >/dev/null 2>&1 && eval `dircolors "$XDG_CONFIG_HOME/dir_colors"`

# User private settings.
[ -f ~/.local/bashrc ] && source ~/.local/bashrc
